version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 19090:9090

  pushgateway:
    image: prom/pushgateway
    ports:
      - 19091:9091
